### ISSUE TITLE
Crashes when building with Visual Studio 2019 on Windows 11

### ISSUE THREAD

**Issue by roponator** [SarahWeiii/CoACD#1]
Hi,

I wanted to try this out on Windows 11 where cmake creates a Visual Studio 2019 project.

But when trying to run it the app crashes. Visual studio also reports potential errors in the code at multiple places.

The error is in triangle.h, line 13988: vertexloop[0] = vertices[i][0];
The vertexloop seems to be allocated incorrectly.

Even after I tried doing a brute malloc instead of the pool it crashed elsewhere.

I tried it on the bottle model.

**Comment by roponator** [comment]
Found the solution: 
replace all unsigned long with int64_t because in C "unsigned long" can be 32 bit, which it is when compiling with visual studio so it discards the upper portion of the 64 bit pointer.

**Comment by SarahWeiii** [comment]
Thank you for pointing it out. I have updated the code.
