### ISSUE TITLE
Specifying max # hulls and max # vertices per hull

### ISSUE THREAD

**Issue by cgokmen** [SarahWeiii/CoACD#10]
Hi,

Thanks a lot for your work on CoACD and for releasing it on GitHub and on PyPI! We have recently started using it instead of V-HACD and have been observing an incredible improvement in the results we get.

We have just one issue: for our use case, which involves using Isaac Sim's GPU dynamics, we need all of our convex decompositions to have fewer than 64 convex hulls, and each of those convex hulls needs to have less than 60 vertices. In V-HACD parameters exist for both of these, which makes it keep reducing until these are reached.

Is there any way we could do this in CoACD? 

Thanks,
Cem

**Comment by SarahWeiii** [comment]
Hi I have added the limitation for # convex hulls, note that with this limitation, the max concavity may exceed the pre-defined threshold, so it is disabled by default.
As for the # vertices, PhysX has the function for limiting max # vertices, and Isaac's backend is PhysX so they should probably expose this feature on their end; you can check whether Isaac has included it: https://nvidia-omniverse.github.io/PhysX/physx/5.1.3/docs/Geometry.html?highlight=cooking#if-only-vertex-points-are-provided.

**Comment by cgokmen** [comment]
Hi Xinyue,

Just wanted to give you an update on this - we did install and try this approach on a number of meshes, it does reduce the number to below the limit however many meshes it produces are not usable (some concave objects like cups, microwaves, cabinets are getting their open side sealed when vhacd can reasonably approximate the same mesh). For now we have decided to use a mix of coacd/vhacd (essentially using coacd first, if it produces more than 64 meshes, use vhacd).

Thanks,
Cem

**Comment by SarahWeiii** [comment]
You may also need to increase the pre-processing resolution to prevent open-side sealed problems.
