### ISSUE TITLE
 error: variable or field ‘debug’ declared void    13 |         inline void debug(spdlog::string_view_t fmt, const Args &...args)

### ISSUE THREAD

**Issue by ccmCCMfk** [SarahWeiii/CoACD#12]
when I try to "make",it occurs.
/home/ustc/PycharmProjects/CoACD/src/logger.h:13:21: error: variable or field ‘debug’ declared void
   13 |         inline void debug(spdlog::string_view_t fmt, const Args &...args)
      |                     ^~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:13:35: error: ‘string_view_t’ is not a member of ‘spdlog’
   13 |         inline void debug(spdlog::string_view_t fmt, const Args &...args)
      |                                   ^~~~~~~~~~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:13:54: error: expected primary-expression before ‘const’
   13 |         inline void debug(spdlog::string_view_t fmt, const Args &...args)
      |                                                      ^~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:19:21: error: variable or field ‘info’ declared void
   19 |         inline void info(spdlog::string_view_t fmt, const Args &...args)
      |                     ^~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:19:34: error: ‘string_view_t’ is not a member of ‘spdlog’
   19 |         inline void info(spdlog::string_view_t fmt, const Args &...args)
      |                                  ^~~~~~~~~~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:19:53: error: expected primary-expression before ‘const’
   19 |         inline void info(spdlog::string_view_t fmt, const Args &...args)
      |                                                     ^~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:25:21: error: variable or field ‘warn’ declared void
   25 |         inline void warn(spdlog::string_view_t fmt, const Args &...args)
      |                     ^~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:25:34: error: ‘string_view_t’ is not a member of ‘spdlog’
   25 |         inline void warn(spdlog::string_view_t fmt, const Args &...args)
      |                                  ^~~~~~~~~~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:25:53: error: expected primary-expression before ‘const’
   25 |         inline void warn(spdlog::string_view_t fmt, const Args &...args)
      |                                                     ^~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:31:21: error: variable or field ‘error’ declared void
   31 |         inline void error(spdlog::string_view_t fmt, const Args &...args)
      |                     ^~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:31:35: error: ‘string_view_t’ is not a member of ‘spdlog’
   31 |         inline void error(spdlog::string_view_t fmt, const Args &...args)
      |                                   ^~~~~~~~~~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:31:54: error: expected primary-expression before ‘const’
   31 |         inline void error(spdlog::string_view_t fmt, const Args &...args)
      |                                                      ^~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:37:21: error: variable or field ‘critical’ declared void
   37 |         inline void critical(spdlog::string_view_t fmt, const Args &...args)
      |                     ^~~~~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:37:38: error: ‘string_view_t’ is not a member of ‘spdlog’
   37 |         inline void critical(spdlog::string_view_t fmt, const Args &...args)
      |                                      ^~~~~~~~~~~~~
/home/ustc/PycharmProjects/CoACD/src/logger.h:37:57: error: expected primary-expression before ‘const’
   37 |         inline void critical(spdlog::string_view_t fmt, const Args &...args)
      |                                                         ^~~~~
CMakeFiles/_coacd.dir/build.make:110: recipe for target 'CMakeFiles/_coacd.dir/src/clip.cpp.o' failed
make[2]: *** [CMakeFiles/_coacd.dir/src/clip.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/_coacd.dir/all' failed
make[1]: *** [CMakeFiles/_coacd.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SarahWeiii** [comment]
It seems like 'string_view_t' is missing in `spdlog`, what version do you use?
I am using 1:1.5.0-1.

**Comment by ccmCCMfk** [comment]
> 


I‘m using  Version 1.11.0

**Comment by ccmCCMfk** [comment]
> It seems like 'string_view_t' is missing in `spdlog`, what version do you use? I am using 1.5.0-1.
with the following command line
$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j

**Comment by ccmCCMfk** [comment]
> > It seems like 'string_view_t' is missing in `spdlog`, what version do you use? I am using 1.5.0-1.
> > with the following command line
> > $ git clone https://github.com/gabime/spdlog.git
> > $ cd spdlog && mkdir build && cd build
> > $ cmake .. && make -j
and I also tried this:conda install -c conda-forge spdlog
it didn't work

**Comment by ccmCCMfk** [comment]
I replace it with spdlog1..5.0,but it still doesn't work.I don't know what's happened.

**Comment by SarahWeiii** [comment]
What platform do you use? Have you tried `sudo apt install -y libspdlog-dev`?

**Comment by ccmCCMfk** [comment]
> What system do you use? Have you tried `sudo apt install -y libspdlog-dev`?

ubuntu18.04,I have tried.it doesn't work

**Comment by Colin97** [comment]
> 

have you tried `make install` for spdlog?

**Comment by ccmCCMfk** [comment]
> 

I didn't,what's the difference between them
