### ISSUE TITLE
AllocatorFooChar missing error when building from source

### ISSUE THREAD

**Issue by samraise** [SarahWeiii/CoACD#18]
Getting this errror when building

`Errors     << CoACD:make /home/ubuntu/workspace/logs/CoACD/build.make.000.log                                                                        
In file included from /home/ubuntu/workspace/build/CoACD/_deps/tbb-src/test/conformance/conformance_allocators.cpp:21:
/home/ubuntu/workspace/build/CoACD/_deps/tbb-src/test/common/allocator_test_common.h: In instantiation of ‘void TestAllocator(TestName, const Allocator&) [with Allocator = std::pmr::polymorphic_allocator<void>]’:
/home/ubuntu/workspace/build/CoACD/_deps/tbb-src/test/conformance/conformance_allocators.cpp:86:123:   required from here
/home/ubuntu/workspace/build/CoACD/_deps/tbb-src/test/common/allocator_test_common.h:284:15: error: no class template named ‘rebind’ in ‘class std::pmr::polymorphic_allocator<void>’
  284 |         using AllocatorFooChar = typename Allocator::template rebind<FooChar>::other;
      |               ^~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [_deps/tbb-build/test/CMakeFiles/conformance_allocators.dir/build.make:76: _deps/tbb-build/test/CMakeFiles/conformance_allocators.dir/conformance/conformance_allocators.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8391: _deps/tbb-build/test/CMakeFiles/conformance_allocators.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:156: all] Error 2`

**Comment by SarahWeiii** [comment]
Do not use `make -j` but use `make main -j` instead.
