### ISSUE TITLE
How to compiling for windows

### ISSUE THREAD

**Issue by hongbin-y** [SarahWeiii/CoACD#19]
This project is amazing. Now i have troubles compiling for windows. I hope you can help me.
The whole process I list here:
1. git clone https://github.com/SarahWeiii/CoACD.git
2. cd CoACD
3. mkdir build
4. cmake ..
After those i got the CoACD.sln：
![image](https://github.com/SarahWeiii/CoACD/assets/31581382/7d2d2c97-f548-4f30-844f-a18c427c997e)
Then I compiled "main" project，but got some errors:
![image](https://github.com/SarahWeiii/CoACD/assets/31581382/deb43536-aefe-4d11-80fb-e731e1b27abe)
Please give me some tips, Thanks!

**Comment by SarahWeiii** [comment]
It is non-trivial to compile the code on Windows, but we provide the Python library for Windows (cross-complied by Linux). We would suggest using the Python library, which can be installed by `pip install coacd`.

**Comment by hongbin-y** [comment]
@SarahWeiii Thanks for your message. I had also tried python, but
![image](https://github.com/SarahWeiii/CoACD/assets/31581382/fc5450b8-f31d-4f8e-b3c5-1b129db62902)
Maybe I missed some important detials. Please point it out! Thanks!

**Comment by SarahWeiii** [comment]
Currently our library supports only win64

**Comment by hongbin-y** [comment]
@SarahWeiii Thanks! My OS is win64.
![image](https://github.com/SarahWeiii/CoACD/assets/31581382/18365e53-151c-40fa-9e1e-6251fa566504)
This is the information that I searched:
[https://stackoverflow.com/questions/52625099/python-incorrectly-detects-32-bit-system-on-windows-8-1-64-bit](url)

**Comment by SarahWeiii** [comment]
You might check if you installed a 32-bit Python.

**Comment by hongbin-y** [comment]
> @SarahWeiii Thanks for your message. I had also tried python, but ![image](https://user-images.githubusercontent.com/31581382/256464889-fc5450b8-f31d-4f8e-b3c5-1b129db62902.png) Maybe I missed some important detials. Please point it out! Thanks!
From this picture, we can know that I installed a 64-bit Python.

**Comment by hongbin-y** [comment]
> You might check if you installed a 32-bit Python.

From the penultimate picture we can know that i installed a 64-bit Python.
