### ISSUE TITLE
relationship between concavity threshold and actual distance

### ISSUE THREAD

**Issue by pca006132** [SarahWeiii/CoACD#21]
hi, I wanted to use this approximate convex decomposition to implement mesh offsetting, but I think I need the concavity metric to be exactly 2r + small delta where r is the offset distance. It seems that the concavity threshold we give can only be within 0.01 to 1, I wonder how that maps to actual distance?

(I am not familiar with geometry so I am not sure if I understand the metrics correctly)

**Comment by SarahWeiii** [comment]
The input object is rescaled into [-1, 1] box and the threshold t corresponds to the actual distance in that scale.

**Comment by pca006132** [comment]
thanks for the quick response!

**Comment by ESui2** [comment]
Do you take a cubic bbox of the original shape as well? Or do you rescale an uneven sized box into a cubic box?
