### ISSUE TITLE
Strange decomposition on simple case.

### ISSUE THREAD

**Issue by John-Nagle** [SarahWeiii/CoACD#22]
![housetest1](https://github.com/SarahWeiii/CoACD/assets/942608/d97e815f-6186-4c44-a1ea-d33ce1b4c679)
Here's a simple test case. 
[househullbug1.zip](https://github.com/SarahWeiii/CoACD/files/12387178/househullbug1.zip)

In the picture, the original model is on the right, and the convex decomposition
is on the left.

Three of the walls, and the ground slab, were convex in the input.
Yet they were subdivided into four parts with more complex geometry.
The fourth wall has a door cutout and a window cutout.
Those disappeared completely during convex decomposition.

This is unexpected.

**Comment by SarahWeiii** [comment]
Hi thank you for pointing out the problem.
I generated the same result using pypi library while running C++ code solves the problem.
I will check if anything is missed while wrapping C++ into Python.

**Comment by John-Nagle** [comment]
Thank you. I used the pre-built version for Linux linked from the Github 
home page. I have not built it from source.

The intended application is to improve the process of creating collision
models for metaverse content for Second Life and Open Simulator. The
Havok convex decomposition program generates geometry with many long
narrow triangles.

					John Nagle

**Comment by SarahWeiii** [comment]
Hi thank you for pointing out the problem.
I checked the remeshed input as shown below and it seems that the remeshing result is already not correct. But also it is weird that the pypi result is not consistent with C++ source code result, I will keep finding the problem.
![image](https://github.com/SarahWeiii/CoACD/assets/28781046/7f41ba57-32d5-4bb3-b9b4-9a2287b8d7b8)

**Comment by John-Nagle** [comment]
![beforeandafter](https://github.com/SarahWeiii/CoACD/assets/942608/330c29c7-2a44-412a-bec5-23b2d36c2216)

Here is a simpler test, which also fails. This is just four walls. There are two meshes. One is a C-shape with three walls, and one is only one wall.

The door and window cutouts, and the floor, are unrelated to the problem. It happens on very simple geometry.

[househullbug2.zip](https://github.com/SarahWeiii/CoACD/files/12392422/househullbug2.zip)

**Comment by SarahWeiii** [comment]
Thanks for providing more information!
The problem is that when trimesh loads the mesh, it turns the input into the following one:
![image](https://github.com/SarahWeiii/CoACD/assets/28781046/fa82428e-bfd8-4aca-a426-7c6f1e94fde3)

I tried to load it using C++ code and it works well. I will keep on finding the solution.

**Comment by SarahWeiii** [comment]
I found your input is an invalid poly mesh for trimesh, you can turn it into a triangular mesh to fix the problem.

**Comment by John-Nagle** [comment]
Thank you. If the input mesh is converted to triangles, the result is a valid set of convex hulls. Now the problem is optimizing the result.

![triangulatedtest](https://github.com/SarahWeiii/CoACD/assets/942608/e63631a7-1182-498a-aee4-0fcc692279f4)

The input model is on the right. The center model was created by CoACD with default settings. The left model was created with **-t 0.01**

![triangulatedwireframe](https://github.com/SarahWeiii/CoACD/assets/942608/84b2de2e-77de-4277-9972-05e8ef9a60e0)

This is the same set of models, shown as wireframes. The hull decomposition is breaking up simple rectangular faces into multiple parts, and rounding edges. So the output has far more triangles than are needed.

I've tried various settings of the program's parameters. Using **-t 0.01** seems to produce the best results.

Files: 
[househullbug3.zip](https://github.com/SarahWeiii/CoACD/files/12403508/househullbug3.zip)

**Comment by SarahWeiii** [comment]
Perhaps try to increase the mcts depth and iteration for a better solution

**Comment by John-Nagle** [comment]
The best settings so far for the example I last sent are:

`./coacd -i work/house1atriang.obj -o house1atriangphy4.obj -md 7 -mi 500 -t 0.01`

Here are a few tries with various parameters. The image at the left is from the parameters above.
![manyiters](https://github.com/SarahWeiii/CoACD/assets/942608/54d77f6a-c553-470a-8b84-dc31961e5b47)

The problem seems to be that the program rounds the corners of right-angle geometry as it makes hulls. Then it has trouble merging the hulls, which no long match at the joint.

It doesn't seem to do that for the examples in the paper which have geometry with right angles at edges.

**Comment by SarahWeiii** [comment]
The round corner is because your input is not manifold and cannot directly apply ACD. And our remeshing algorithm introduces round artifacts. The example in the paper is using manifold inputs.

You can use other remeshing algorithms to preserve the corners and turn off our remeshing.

**Comment by John-Nagle** [comment]
That is helpful. That was supposed to be a valid manifold model, and I am not sure why it is not. Blender's manifold checker does not find any errors, and I can't find any by hand. Nor can I find interior faces or reversed normals. I will create more test cases to try to pin this problem down.

**Comment by John-Nagle** [comment]
[househullbug4.zip](https://github.com/SarahWeiii/CoACD/files/12482147/househullbug4.zip)

Here is a simpler test case. CoACD considers this an "unclosed mesh", but Blender considers it a valid manifold. This test case is so simple that it can be checked visually or by hand.

**Comment by SarahWeiii** [comment]
You can turn off the remeshing manually by `-pm off`, and I will check the manifold check code later.

**Comment by John-Nagle** [comment]
![assumemanifold](https://github.com/SarahWeiii/CoACD/assets/942608/ed37c3ee-eabf-40c6-9016-c918372b6a44)

Much better with "-pm off"! The four-sided box is perfect. The simple house has some minor problems. I will try adjusting the parameters for that tomorrow.

**Comment by John-Nagle** [comment]
![goodhull1](https://github.com/SarahWeiii/CoACD/assets/942608/d51c9500-ec52-4a30-ae57-8a145cc37c84)

A good result, at last.

Settings:

`./coacd -i work/house1atriang.obj -o house1atriangphy5b.obj -pm off -md 7 -t 0.02`

Results are very sensitive to **t**. 

![goodandbadhulls1](https://github.com/SarahWeiii/CoACD/assets/942608/450cbdb9-f4a9-4563-80b0-96032e6883aa)
From left to right:

- t = 0.05  The door hole has been shrunk. Unsuitable for a collision model.
- t = 0.02  Good results, except that the window hole is slightly distorted.
- t = 0.01  Door and window are perfect but the big flat sides do not get merged into single hulls.

I will try some more complex models soon. Thanks.

**Comment by SarahWeiii** [comment]
Yes that is for sure since the terminate condition of the algorithm is `t`, and `t` controls the collision condition of the result (the distance between the input and output). So larger `t` has a worse approximation but can ensure fewer components, and you need to balance that based on your use case.
