### ISSUE TITLE
Is possible to see only the preprocessed mesh?

### ISSUE THREAD

**Issue by fire** [SarahWeiii/CoACD#25]
Hi,

Do you know what settings allows me to see the preprocessed mesh without the CoACD algorithm generation?

Wanted to debug the preprocessor.

**Comment by SarahWeiii** [comment]
Currently the Python library does not have this feature. You can modify the C++ code (main.cpp) and save the mesh after preprocess.

**Comment by fire** [comment]
Would you like any syntax for it in the command line?

**Comment by SarahWeiii** [comment]
Do you need it in Python package or in C++?

**Comment by fire** [comment]
I would prefer c++ as I wanted to use it in a command line tool called by Godot Engine. 

Remember the problem space being very difficult.

1. openvdb is used to force the geometric shape to be manifold
2. CoACD's is then applied

**Comment by SarahWeiii** [comment]
I added a command for saving preprocessed mesh, you can use `-ro` or `--remesh-output` to designate the output path. It saves the mesh after preprocessing and normalization to [-1,1] (if disabling the preprocess, it outputs the normalized mesh).
