### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by ray8828** [SarahWeiii/CoACD#3]
Hi thanks for sharing this great work, I'm using CoACD to replace VHACD to build some robot simulation envs, but I found that when I specify the output to be .wrl format, the output is still in .obj format, and I'm wondering is there a way to save saperate cvx hulls so I can load them saperately to the simulator? Thanks

**Comment by ray8828** [comment]
It turns out that my output path has an `obj` in the path, so the plain string replace it to wrl... resolved

**Comment by SarahWeiii** [comment]
Yes the output saves both obj and wrl in the same directory.
As for the separate cvx hulls, we can add this option in the future version. Thanks for pointing it out.

**Comment by ray8828** [comment]
I figured it out with your function `SaveOBJS` that's useful, thanks!
