### ISSUE TITLE
Crash when decomposing

### ISSUE THREAD

**Issue by Pindrought** [SarahWeiii/CoACD#34]
I have a model of a cottage and the library is crashing when I try to decompose it. I am not sure if i'm doing something wrong.
![image](https://github.com/SarahWeiii/CoACD/assets/39708313/7bccacf7-abc0-4110-a52d-67c05c62f61e)

[Here is the .obj file for the cottage example.](https://drive.google.com/file/d/1c4LEwmiudMVFr3zTlJFX5uCksfuiHxy6/view?usp=sharing)

[Here is a minimal code example that builds all of the verts/indices and attempts to decompose them.](https://pastebin.com/xzKm03u7) 
I was originally trying with **preprocess = ""** but even with **preprocess = "auto"** it still crashes so I think the cause is something else.

Thank you very much for your library!

**Edit: When testing it out, it seems like if I increase the threadhold to 0.2 it will work, but obviously it produces results that are less than desirable with a threshold that high and even with the increased threshold preprocess must be on or it crashes.**

**Comment by SarahWeiii** [comment]
Do you have error info?

**Comment by Pindrought** [comment]
When using a threshold of 0.05, I am seeing this.
![image](https://github.com/SarahWeiii/CoACD/assets/39708313/7f3c07f6-71c5-4367-b342-45a33fc6392f)

![image](https://github.com/SarahWeiii/CoACD/assets/39708313/d5f7fff0-0b87-4191-bb53-d5e59d8bd421)


I don't have any info in the logger suggesting an error. The program is just crashing.

**Comment by Pindrought** [comment]
I am working on trying to figure out where exactly this is happening.
Something to note - it does not crash with the release version of the libs.
It is only crashing in debug.

**Comment by eliphatfs** [comment]
The two code should be compiled into the same binary theoretically; perhaps this actually relates to a bug with your specific version of Visual Studio/MSVC. The input object is doing well on the 1.0.0 official release.

**Comment by Pindrought** [comment]
I'm using the latest version of MSVC/the latest compiler.

**Comment by eliphatfs** [comment]
This is a problem in the upstream quickhull library, we could fix it here temporarily and report to its author(s)

**Comment by Pindrought** [comment]
Thanks for the clarification I didn't realize that was from a different library.
