### ISSUE TITLE
Reduce number of vertices in each convex hull

### ISSUE THREAD

**Issue by neemoh** [SarahWeiii/CoACD#37]
I was wondering if there is a way to reduce the number of vertices of each convex hull. 

Compared to VHACD I get a lot more vertices per convex hull with COACD. Although I am quite impressed with the quality of the decomposition of COACD, the high number of vertices will affect collision checking too just like having too many convex hulls.

Here is an example. Compare for instance the VHACD2 MEDIUM case that has 8 convex hulls with 369 vertices and the COACD LOW case that has a similar 7 convex hulls but with 10 times more vertices:

![image](https://github.com/SarahWeiii/CoACD/assets/16369053/636943ab-a349-4360-afd9-5e1411a1fa8f)

**Comment by SarahWeiii** [comment]
Thanks for bringing up the issue! I'll look into improving it when I have a moment to spare.

**Comment by SarahWeiii** [comment]
btw you can turn off the pre-processing if your input is manifold
if it is not, one quick way to fix the problem is to manually remesh + simplify the input

**Comment by neemoh** [comment]
Thanks for tho hint Sarah. Taking some off now, and will check when back in the office in a couple of weeks. Will the pre processing affect the number of output vertices? 

Unfortunately, manual re meshing of the input won't be a great option, because we need something that works with little intervention from users. The VHACD has a parameter to specify the maximum number of vertices per convex hull (we use the default 64). Would such a parameter be feasible to have in COACD?

**Comment by SarahWeiii** [comment]
oh sorry for the late reply. The results are convex hulls of the original mesh so the pre-processing can reduce the output vertices.
I planned to add some automatic pre-processing but haven't finished. It can help reduce the vertices but cannot specify the maximum number of vertices per convex hull.

**Comment by MagixGames** [comment]
Many months later but I too would love to see this feature realized. I've been trying to use this tool for Unity collision and another proprietary collision engine, but both require no more than 256 vertices and sometimes meshes with more than that are output.

**Comment by SarahWeiii** [comment]
Hi the feature is added; use `-d` to enable convex hull max vertex contraint and `-dt` to set the max value.
