### ISSUE TITLE
Does CoACD use manifold plus?

### ISSUE THREAD

**Issue by fire** [SarahWeiii/CoACD#7]
Can you clarify?

I wish to use CoACD but any licenses in the source file that are non opensource licensed means the whole system is non opensource.

https://github.com/SarahWeiii/CoACD#license

Can you separate the non opensource code to a different folder so I can strip it?

1. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/ManifoldPlus.h
2. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/Manifold_p.h
3. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/GridIndex_p.h
4. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/IO_p.cc
5. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/IO_p.h
6. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/Intersection.cpp (has no license)
7. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/Octree_p.cc
8. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/Octree_p.h
9. https://github.com/SarahWeiii/CoACD/blob/main/src/manifold/types_p.h

**Comment by Colin97** [comment]
Yes, CoACD uses ManifoldPlus as a pre-processing. You can disable this pre-processing by the option `--no-manifold-plus` or `-nmp`.
If you want to use our code for commercial use and remove the ManifoldPlus library, you can delete all files in the manifold/ folder.

**Comment by fire** [comment]
Thanks for your response.
