### ISSUE TITLE
Threshold too high

### ISSUE THREAD

**Issue by Pippo809** [SarahWeiii/CoACD#8]
I am trying to compute the convex decomposition of a mechanism but the threshold parameter is too high and does not allow to obtain a usable result.
![Original file](https://user-images.githubusercontent.com/91191644/221906959-be2dcc30-b0b2-4a16-ba28-428a53446e15.png)

![Decomposed file](https://user-images.githubusercontent.com/91191644/221907517-68a272cc-69cb-4426-acaa-eafc8b9f2458.png)

What can I do to obtain a better result?

**Comment by Colin97** [comment]
Have you ever tried a lower concavity threshold by using -t option?

**Comment by Pippo809** [comment]
Yes, those are the results with the lowest setting possible (-t 0.01) I was wondering why there wasn't an option to go lower

**Comment by Colin97** [comment]
Would you mind sharing your input files?

**Comment by SarahWeiii** [comment]
Hi the pre-processing will remesh non-manifold mesh and may lose some details. So the problem may not be caused by the threshold. If your mesh is manifold, you can use `-np` to turn off the pre-process; if not, you can try to tune the remeshing resolution by `-pr`.

**Comment by AbdeAltheria** [comment]
As @SarahWeiii commented, it may be mostly problem of the non-manifold preprocessing. In some applications, I tried using CoACD without pre-processing for general meshes (manifold and non-manifold) and it works in most cases. In the worst of the cases, it diverges a little bit, but it converges eventually for every mesh.

**Comment by SarahWeiii** [comment]
If not using pre-processing for non-manifold meshes, there may be trouble in the triangulation of newly generated parts during cutting, which can lead to redundant convex hulls. But in general, it should not affect the approximation of the original shape.
