### ISSUE TITLE
Troubles compiling for windows

### ISSUE THREAD

**Issue by fire** [SarahWeiii/CoACD#9]
1. spdlog is missing
2. openvdb is missing
3. boost is missing

Looking into this.

**Comment by fire** [comment]
1. use msys
2. pacman -S mingw-w64-x86_64-boost
3. pacman -S mingw-w64-x86_64-openvdb
4.

**Comment by fire** [comment]
Some errors:

```
src/btConvexHull/btAlignedAllocator.cpp:71:31: error: cast from 'char*' to 'long unsigned int' loses precision [-fpermissive]
   71 |         offset = (alignment - (unsigned long)(real + sizeof(void*))) & (alignment - 1);
```

**Comment by fire** [comment]
This is sufficiently difficult that making release builds for windows might be a good idea.

**Comment by SarahWeiii** [comment]
Hi thank you for the suggestions. Our code was mainly tested on Linux, have you tried using WSL to run the code on Windows?

**Comment by yetigit** [comment]
> Hi thank you for the suggestions. Our code was mainly tested on Linux, have you tried using WSL to run the code on Windows?

i'm sure it compiles fine on linux but a native windows build would be more than welcome for this fantastic library

**Comment by fire** [comment]
I am unable to compile for windows.

**Comment by yetigit** [comment]
@fire please use my fork https://github.com/yetigit/CoACD and checkout to `master` to build on windows.
```
git clone --recursive https://github.com/yetigit/CoACD.git
git fetch origin master
git checkout master
```
and use vcpkg with cmake. 

example of using the app :
`coacdapp.exe -i chair.obj -o chairout.obj -np -mn 10 -t 0.4 -c 4` 

the parameter `-np` is needed to speed things up if you are sure you have a watertight manifold mesh
the new parameter `-c` (max number of convex hulls) is super useful.

-------------------------------------

## The problem we had here on windows :

- is the namespace pollution. there was a dozen of `using namespace std` (this was the biggest problem and I had to go in there and manually prepend `std::`  to everything for hours).
- couple of incorrect includes
- dependencies not referenced in the cmake file
- unneeded instructions in the cmake file 

@SarahWeiii i am not familiar with collaborating using forks and I have some other work to do but do consider the changes I made on my fork, on `master` https://github.com/yetigit/CoACD and maybe let's try to merge it later, cheerios

**Comment by fire** [comment]
```
vcpkg install OpenVDB
git clone --recursive https://github.com/yetigit/CoACD.git
git fetch origin master
git checkout master
cd CoACD
mkdir build
cd build
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
ninja
```

Work in progress

**Comment by SarahWeiii** [comment]
Thank you @fire @yetigit for the effort of compiling CoACD on Windows! @yetigit you could simply send a pull request to me and I can merge the code into the main branch.

**Comment by Shayp277** [comment]
Hi everyone,
I've been struggeling for  couple of days now to try and run coacd on windows with no success.

when I "pip install coacd" the installation is complete but then when I try to import it I get:

PS C:\Users\shayp> & C:/Users/shayp/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/Users/shayp/Desktop/Untitled-1.py
Traceback (most recent call last):
  File "C:\Users\shayp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\coacd\__init__.py", line 19, in <module>
    _lib = ctypes.CDLL(os.path.join(os.path.dirname(__file__), "lib_coacd.so"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\shayp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\coacd\lib_coacd.so' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\shayp\Desktop\Untitled-1.py", line 1, in <module>
    import coacd
  File "C:\Users\shayp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\coacd\__init__.py", line 21, in <module>
    _lib = ctypes.CDLL(os.path.join(os.path.dirname(__file__), "lib_coacd.dll"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\shayp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\coacd\lib_coacd.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by Shayp277** [comment]
> Hi everyone, I've been struggeling for couple of days now to try and run coacd on windows with no success.
> 
> when I "pip install coacd" the installation is complete but then when I try to import it I get:
> 
> PS C:\Users\shayp> & C:/Users/shayp/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/Users/shayp/Desktop/Untitled-1.py Traceback (most recent call last): File "C:\Users\shayp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\coacd__init__.py", line 19, in _lib = ctypes.CDLL(os.path.join(os.path.dirname(**file**), "lib_coacd.so")) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes__init__.py", line 374, in **init** self._handle = _dlopen(self._name, mode) FileNotFoundError: Could not find module 'C:\Users\shayp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\coacd\lib_coacd.so' (or one of its dependencies). Try using the full path with constructor syntax.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "c:\Users\shayp\Desktop\Untitled-1.py", line 1, in import coacd File "C:\Users\shayp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\coacd__init__.py", line 21, in _lib = ctypes.CDLL(os.path.join(os.path.dirname(**file**), "lib_coacd.dll")) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes__init__.py", line 374, in **init** self._handle = _dlopen(self._name, mode) FileNotFoundError: Could not find module 'C:\Users\shayp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\coacd\lib_coacd.dll' (or one of its dependencies). Try using the full path with constructor syntax.

Is it possible to run this library on an x86_64 os?

**Comment by SarahWeiii** [comment]
Our library supports x86_64 os. Have you installed `vc redist`?

**Comment by SarahWeiii** [comment]
We have updated the pypi package, including all the .dll in the wheel. You could install the latest (0.0.4) and try if it works.

**Comment by Shayp277** [comment]
> We have updated the pypi package, including all the .dll in the wheel. You could install the latest (0.0.4) and try if it works.

I have both vc redist and visual studio.
How do I get version 0.0.4? pip install coacd is giving me version 0.0.3
thanks

**Comment by SarahWeiii** [comment]
You may try `pip install coacd --upgrade`

**Comment by Shayp277** [comment]
Hi, reinstalled the coacd and now its the 0.0.4 version.
Guess I tried before the package was updated in the pypi.
Now everything works great!
thank you very much for this awesome library and quick response :)
